on:
  push:

jobs:
  build:
    env:
      SIZE: 1024

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - run: |
          cat > test.csproj << EOM
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>netstandard2.0</TargetFramework>
            </PropertyGroup>
            <ItemGroup>
              <EmbeddedResource Include="embedded.txt" />
            </ItemGroup>
          </Project>
          EOM

      - run: dd if=/dev/zero of=embedded.txt count=${{ env.SIZE }} bs=1024

      - run: dotnet build
