on:
  push:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
        
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [3.1.x, 2.1.x]
        app: ["dotnet nuget", "nuget"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        size: [65536]

    env:
      VERSION: 1.0.0-g${{ github.sha }}-${{ matrix.size }}

    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - run: |
          cat > test.csproj << EOM
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>netstandard2.0</TargetFramework>
            </PropertyGroup>
            <ItemGroup>
              <EmbeddedResource Include="embedded.txt" />
            </ItemGroup>
          </Project>
          EOM

      - run: dd if=/dev/random of=embedded.txt count=${{ matrix.size }} bs=1024

      - run: dotnet pack -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} -p:Version=${{ env.VERSION }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}
          dotnet-version: ${{ matrix.dotnet-version }}
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - run: ls -l bin/Debug/*.nupkg

      - run: ${{ matrix.app }} push bin/Debug/*.nupkg
